services:
    test_app_user.message_manager:
            class: TestApp\UserBundle\Manager\MessageManager
            arguments: [ @doctrine.orm.entity_manager ]

    test_app_user.authentication_success_handler:
        class: TestApp\UserBundle\EventListener\AuthenticationSuccessHandler
        arguments: [ @test_app_notification.mailer, @test_app_user.message_manager,"%after_login_path%" ]
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }



